openapi: 3.0.0
info:
  title: B2B Marketplace API - Authentication
  version: 1.0.0

paths:
  /api/auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Create a new customer account. Vendors can register and apply for vendor status after registration.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 50
                  example: "John Doe"
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  minLength: 6
                  example: "SecurePass123"
                phone:
                  type: string
                  example: "+1234567890"
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Registration successful"
                  token:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: Validation error or email already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/auth/login:
    post:
      tags:
        - Authentication
      summary: Login to existing account
      description: Authenticate with email and password to receive a JWT token.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  example: "SecurePass123"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successful"
                  token:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/auth/me:
    get:
      tags:
        - Authentication
      summary: Get current user
      description: Retrieve the currently authenticated user's profile.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /api/auth/profile:
    put:
      tags:
        - Authentication
      summary: Update user profile
      description: Update the current user's profile information.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    state:
                      type: string
                    zipCode:
                      type: string
                    country:
                      type: string
      responses:
        "200":
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /api/auth/change-password:
    put:
      tags:
        - Authentication
      summary: Change password
      description: Change the current user's password.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
                  minLength: 6
      responses:
        "200":
          description: Password changed successfully
        "400":
          description: Current password is incorrect
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /api/auth/deactivate:
    put:
      tags:
        - Authentication
      summary: Deactivate account
      description: Deactivate the current user's account.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Account deactivated successfully
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /api/auth/web3-key:
    get:
      tags:
        - Authentication
      summary: Get Web3 key
      description: Retrieve the user's Web3/blockchain wallet key for escrow operations.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Web3 key retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                    description: Blockchain wallet address
                  hasKey:
                    type: boolean
        "401":
          $ref: "#/components/responses/UnauthorizedError"
